### ISSUE TITLE
Icon search on humbleicons.com is case-sensitive

### ISSUE THREAD

**Issue by martincyoung** [zraly/humbleicons#4]
The search function on humbleicons.com is case sensitive:

![image](https://user-images.githubusercontent.com/4625809/180277010-064e08f1-d385-4af3-a04a-af4cdafec1f8.jpeg)

![image](https://user-images.githubusercontent.com/4625809/180277038-d987f8c7-8c9c-4aa3-9e1e-b3eac5c9f44f.jpeg)

I can't find the site code to make the PR myself.

**Comment by zraly** [comment]
Fixed, thanks!
